source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'puma'
gem 'rackup'

group :test do
  gem 'minitest'
  gem 'rack-test'
end

group :development, :test do
  gem 'slim_lint', require: false
end
