# config/tax_brackets.yml
mfj_2023:
  ordinary:
    - { income: 0, rate: 0.10 }
    - { income: 22000, rate: 0.12 }
    - { income: 89450, rate: 0.22 }
    - { income: 201050, rate: 0.24 }
  capital_gains:
    - { income: 0, rate: 0.0 }
    - { income: 89250, rate: 0.15 }
    - { income: 553850, rate: 0.20 }
  irmaa_part_b:
    - { income_threshold: 97000, surcharge_per_person: 65.90 }
    - { income_threshold: 194000, surcharge_per_person: 164.90 }
    - { income_threshold: 386000, surcharge_per_person: 329.70 }
single_2023:
  ordinary:
    - { income: 0, rate: 0.10 }
    - { income: 11000, rate: 0.12 }
    - { income: 44725, rate: 0.22 }
    - { income: 100525, rate: 0.24 }
  irmaa_part_b:
    - { income_threshold: 97000, surcharge_per_person: 65.90 }
    - { income_threshold: 129000, surcharge_per_person: 164.90 }
    - { income_threshold: 161000, surcharge_per_person: 296.20 }
    - { income_threshold: 193000, surcharge_per_person: 329.70 }
    - { income_threshold: 500000, surcharge_per_person: 359.40 }
    - { income_threshold: Infinity, surcharge_per_person: 395.60 }
