# config/tax_brackets.yml
---
# Standard Deductions
standard_deduction_mfj_2023: 27700
standard_deduction_single_2023: 13850

# Married Filing Jointly Brackets for 2023
mfj_2023:
  ordinary:
    - { income: 201050, rate: 0.24 }
    - { income: 94300, rate: 0.22 }
    - { income: 22000, rate: 0.12 }
    - { income: 0, rate: 0.10 }
  capital_gains:
    - { income: 583750, rate: 0.20 }
    - { income: 94050, rate: 0.15 }
    - { income: 0, rate: 0.0 }
  social_security_provisional_income:
    phase1_start: 32000
    phase2_start: 44000
  irmaa_part_b:
    - { income_threshold: 206000, surcharge_per_person: 0 }
    - { income_threshold: 258000, surcharge_per_person: 838.8 }
    - { income_threshold: 322000, surcharge_per_person: 2096.4 }
    - { income_threshold: 386000, surcharge_per_person: 3354.0 }
    - { income_threshold: 750000, surcharge_per_person: 4611.6 }
    - { income_threshold: .inf, surcharge_per_person: 5031.6 }
  irmaa_part_d:
    - { income_threshold: 206000, surcharge_per_person: 0 }
    - { income_threshold: 258000, surcharge_per_person: 147.6 }
    - { income_threshold: 322000, surcharge_per_person: 380.4 }
    - { income_threshold: 386000, surcharge_per_person: 613.2 }
    - { income_threshold: 750000, surcharge_per_person: 846.0 }
    - { income_threshold: .inf, surcharge_per_person: 921.6 }

# Single Filer Brackets for 2023
single_2023:
  ordinary:
    - { income: 100525, rate: 0.24 }
    - { income: 47150, rate: 0.22 }
    - { income: 11000, rate: 0.12 }
    - { income: 0, rate: 0.10 }
  capital_gains:
    - { income: 291875, rate: 0.20 }
    - { income: 47025, rate: 0.15 }
    - { income: 0, rate: 0.0 }
  social_security_provisional_income:
    phase1_start: 25000
    phase2_start: 34000
  irmaa_part_b:
    - { income_threshold: 103000, surcharge_per_person: 0 }
    - { income_threshold: 129000, surcharge_per_person: 838.8 }
    - { income_threshold: 161000, surcharge_per_person: 2096.4 }
    - { income_threshold: 193000, surcharge_per_person: 3354.0 }
    - { income_threshold: 500000, surcharge_per_person: 4611.6 }
    - { income_threshold: .inf, surcharge_per_person: 5031.6 }
  irmaa_part_d:
    - { income_threshold: 103000, surcharge_per_person: 0 }
    - { income_threshold: 129000, surcharge_per_person: 147.6 }
    - { income_threshold: 161000, surcharge_per_person: 380.4 }
    - { income_threshold: 193000, surcharge_per_person: 613.2 }
    - { income_threshold: 500000, surcharge_per_person: 846.0 }
    - { income_threshold: .inf, surcharge_per_person: 921.6 }
