# config/tax_brackets.yml
---
standard_deduction_mfj_2023: 27700

mfj_2023:
  ordinary:
    - { income: 201050, rate: 0.24 }
    - { income: 94300, rate: 0.22 }
    - { income: 22000, rate: 0.12 }
    - { income: 0, rate: 0.10 }
  ltcg:
    - { income: 583750, rate: 0.20 }
    - { income: 94050, rate: 0.15 }
    - { income: 0, rate: 0.0 }
  irmaa_part_b:
    - { income_threshold: 206000, surcharge_per_person: 0 }
    - { income_threshold: 258000, surcharge_per_person: 838.8 } # 69.90 * 12
    - { income_threshold: 322000, surcharge_per_person: 2096.4 } # 174.70 * 12
    - { income_threshold: 386000, surcharge_per_person: 3354.0 } # 279.50 * 12
    - { income_threshold: 750000, surcharge_per_person: 4611.6 } # 384.30 * 12
    - { income_threshold: .inf, surcharge_per_person: 5031.6 } # 419.30 * 12
  irmaa_part_d:
    - { income_threshold: 206000, surcharge_per_person: 0 }
    - { income_threshold: 258000, surcharge_per_person: 147.6 } # 12.30 * 12
    - { income_threshold: 322000, surcharge_per_person: 380.4 } # 31.70 * 12
    - { income_threshold: 386000, surcharge_per_person: 613.2 } # 51.10 * 12
    - { income_threshold: 750000, surcharge_per_person: 846.0 } # 70.50 * 12
    - { income_threshold: .inf, surcharge_per_person: 921.6 } # 76.80 * 12

ny_brackets_2025_mfj:
  - [0, 0.04]
  - [17150, 0.045]
  - [23600, 0.0525]
  - [27900, 0.0585]
  - [161550, 0.0625]
  - [323200, 0.0685]
  - [2155350, 0.0965]
  - [5000000, 0.103]
  - [25000000, 0.109]
